language: julia

os:
  - linux
  - osx

julia:
  - 0.4
  - release
  - nightly

sudo: required

git:
  depth: 9999

notifications:
  email: false

before_install:
  - if [ `uname` == "Linux" ]; then unset DYLD_LIBRARY_PATH; bash travisCI/setup_travis_linux.sh; fi
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-3.3.2-Darwin-x86_64.tar.gz;
    tar -zxf cmake-3.3.2-Darwin-x86_64.tar.gz;
    export PATH=`pwd`/cmake-3.3.2-Darwin-x86_64/CMake.app/Contents/bin:$PATH; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz;
    tar -xzf cmake-3.3.2-Linux-x86_64.tar.gz;
    sudo cp -fR cmake-3.3.2-Linux-x86_64/* /usr;
    export PATH=`pwd`/cmake-3.3.2-Linux-x86_64/bin:$PATH; fi

script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("NLPModels"); Pkg.test("NLPModels"; coverage=true)'

after_success:
  - julia -e 'for pkg in ["Documenter", "JuMP", "ForwardDiff"] Pkg.add(pkg); end'
  - julia -e 'Pkg.clone("https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl")'
  - julia -e 'cd(Pkg.dir("NLPModels")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("NLPModels")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
