language: julia

os:
  - linux
  - osx

julia:
  - 0.4
  - release
  - nightly

sudo: required

git:
  depth: 9999

notifications:
  email: false

# Github/Travis bug
# branches:
#   only:
#     - master

before_install:
  - if [ `uname` == "Linux" ]; then unset DYLD_LIBRARY_PATH; bash travisCI/setup_travis_linux.sh; fi
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("NLPModels"); Pkg.test("NLPModels"; coverage=true)'

after_success:
  - julia -e 'for pkg in ["Documenter", "JuMP", "ForwardDiff"] Pkg.add(pkg); end'
  - julia -e 'Pkg.clone("https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl")'
  - julia -e 'cd(Pkg.dir("NLPModels")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("NLPModels")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
