environment:
  matrix:
  - JULIAVERSION: "stable/win32"
  - JULIAVERSION: "stable/win64"

install:
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile($("http://status.julialang.org/"+$env:JULIAVERSION), "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "versioninfo(); Pkg.init(); Pkg.clone(\"https://github.com/dpo/AmplNLReader.jl.git\"); Pkg.checkout(\"AmplNLReader\", \"nlpmodel\"); Pkg.build(\"AmplNLReader\");"
  - C:\projects\julia\bin\julia -e "versioninfo(); Pkg.init(); Pkg.clone(\"JuMP\"); Pkg.clone(pwd(), \"NLPModels\"); Pkg.build(\"NLPModels\");"

test_script:
  - C:\projects\julia\bin\julia -e "Pkg.test(\"NLPModels\")"
