name = "NLPModels"
uuid = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
version = "0.8.2"

[deps]
FastClosures = "9aa1b823-49e4-5ca5-8b0f-3971ec8bab6a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
FastClosures = "≥ 0.2.1"
ForwardDiff = "≥ 0.9.0"
LinearOperators = "≥ 0.5.0"
julia = "^1.0.0"
